### ISSUE TITLE
Umbraco 15: No more UmbracoAPIController

### ISSUE THREAD

**Issue by sofietoft** [umbraco/UmbracoDocs#6466]
## Update code samples using the obsolete UmbracoAPIController

In Umbraco 15, we are removing the UmbracoAPIController.
This means we should remove all references to the UmbracoAPIController in the documentation.

### What needs to be done

In most scenarios, the UmbracoAPIController should be directly swappable with a standard Controller.

**Testing is required to ensure the code compiles after making the swap.**

Use **Umbraco 14**, where the UmbracoAPIController is already marked as obsolete.
You can also use the Release Candidate for Umbraco 15.

Follow these steps:

1. Locate a code snippet that uses the UmbracoAPIController
2. Put the code into a project
3. Swap UmbracoAPIController with Controller
4. Run the project to test whether the code compiles

Depending on the result of this test, do the following:

- **It compiles - woohoo! 🥳**
  - Make a PR for the change and keep the task in this Issue checked ✅
- **It doesn't compile 😞**
  - Add the relevant information as a comment on this issue, and we'll pick it up for further investigation 🔍

### Code snippets that need to be tested

I'll add checkmarks to the articles that have been updated 🙌 

* [x] [Extending > Database](https://docs.umbraco.com/umbraco-cms/extending/database#working-with-data-in-custom-database-tables)
* [x] [Image Cropper](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/image-cropper#add-values-programmatically)
* [x] [Block Grid Editor](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-grid-editor#creating-a-block-grid-programmatically) -- Very technical!
* [x] [Debugging > Logging](https://docs.umbraco.com/umbraco-cms/fundamentals/code/debugging/logging#writing-to-the-log)
* [x] [Unit Testing](https://docs.umbraco.com/umbraco-cms/implementation/unit-testing#testing-an-umbracoapicontroller)
* [x] [Common Pitfalls: Static references to scoped references](https://docs.umbraco.com/umbraco-cms/reference/common-pitfalls#static-references-to-scoped-instances-such-as-umbracohelper)
* [x] [Mapping](https://docs.umbraco.com/umbraco-cms/reference/mapping#full-example)
* [x] [IoC and Dependency injection](https://docs.umbraco.com/umbraco-cms/reference/using-ioc#injecting-dependencies-into-a-class)
* [x] [Cache > Tags](https://docs.umbraco.com/umbraco-cms/reference/cache/examples/tags#api)
* [x] [Relation Service](https://docs.umbraco.com/umbraco-cms/reference/management/using-services/relationservice#automatically-relate-to-root-node)
* [x] [Querying > ITagQuery](https://docs.umbraco.com/umbraco-cms/reference/querying/itagquery#how-to-reference-itagquery)
* [x] [Querying > Umbraco Context](https://docs.umbraco.com/umbraco-cms/reference/querying/umbraco-context#how-to-reference-umbracocontext)
* [x] [Getting started with Entity Framework (EF) Core](https://docs.umbraco.com/umbraco-cms/tutorials/getting-started-with-entity-framework-core#working-with-the-data-in-the-custom-database-tables)
```[tasklist]
### Tasks
```
